# Generated by Django 4.0.4 on 2022-11-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='history',
            field=models.TextField(default=''),
        ),
    ]
