# Generated by Django 4.0.4 on 2022-10-23 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='isUse',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('exp', models.IntegerField()),
                ('money', models.IntegerField()),
                ('characters', models.TextField()),
                ('skins', models.TextField()),
                ('pets', models.TextField()),
                ('stadiums', models.TextField()),
                ('score', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('jump', models.IntegerField()),
                ('energy', models.IntegerField(default=120)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.account')),
            ],
        ),
    ]
